pisite/logs/urls.py
from django.conf.urls import patterns, url
from logs import views

urlpatterns = patterns('',
  # /logs/
  url(r'^$', views.index, name='index'),
  # /logs/logname
  url(r'^(?P<logName>\S+)/$', views.log, name="individualLog")
)

pisite/pisite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from home import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pisite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^logs/', include('logs.urls', namespace="logs")),
    url(r'^motionSound/', include('motionSound.urls', namespace="motionSound")),
    url(r'^admin/', include(admin.site.urls)),

    # Pages within the home app
    #
    # Home page
    url(r'^$', views.index, name="home"),
    # Sound upload page
    #url(r'^uploadSound$', views.uploadSound, name="uploadSound")
)

pisite/logs/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Log(models.Model):
  name = models.CharField(max_length=50)
  filePath = models.CharField(max_length=300)
  defaultLinesToShow=100
  
  def getFileContents(self):
    logFile = open(settings.BASE_DIR + "/" + self.filePath)
    contents = logFile.read()
    logFile.close()
    return contents

  def getLastNLines(self, n=defaultLinesToShow):
    logFile = open(settings.BASE_DIR + "/" + self.filePath)
    lines = logFile.readlines()
    logFile.close()

    lastNLines = "".join(lines[-n:])
    return lastNLines

  def __unicode__(self):
    return self.name

pisite/logs/forms.py
from django import forms
from logs.models import Log

class LineCountForm(forms.Form):
  linesToFetch = forms.IntegerField(label="Number of lines to show (0 for all)", min_value=0, initial=Log.defaultLinesToShow)

pisite/logs/views.py
from django.shortcuts import render, get_object_or_404

from logs.models import Log
from logs.forms import LineCountForm

# Create your views here.
def index(request):
  logList = Log.objects.all()
  context = {'logList': logList}
  return render(request, 'logs/index.html', context)

def log(request, logName):
  lineCount = Log.defaultLinesToShow
  # Handle POSTS
  if request.method == 'POST':
    form = LineCountForm(request.POST)
    if form.is_valid():
      lineCount = form.cleaned_data['linesToFetch']
  else:
    form = LineCountForm()

  log = get_object_or_404(Log, name=logName)
  logText = log.getLastNLines(n=lineCount)

  context = {'logName': log.name, 'logText': logText, 'form': form}
  return render(request, 'logs/log.html', context)

pisite/logs/templates/logs/index.html
{% if logList %}
  {% for log in logList %}
    <h1><a href="{% url 'logs:individualLog' log.name %}">{{ log.name }}</a></h1>
    <textarea class="scrolled" readonly cols="100" rows="10">{{ log.getLastNLines }}</textarea>
  {% endfor %}
{% else %}
  <p> No logs </p>
{% endif %}

{% load staticfiles %}
<script src="{% static 'logs/scrollTextAreas.js' %}"></script>

pisite/logs/templates/logs/log.html
<h1>Log file for {{ logName }}</h1>
<textarea readonly cols="100" rows="25">{{ logText }}</textarea>

<form name="lineCount" action="{% url 'logs:individualLog' logName %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>

{% load staticfiles %}
<script src="{% static 'logs/scrollTextAreas.js' %}"></script>